apiVersion: v2
name: apptalleres
description: App para talleres confortauto
type: application

# Versión del Chart (el empaquetado)
version: 0.1.0

# Versión de la aplicación que se está desplegando
appVersion: "1.0.0"
