# values.yaml
appName: transport-documents-prod #cambiame 
replicaCount: 1
ingress:
  enabled: true
  host: "transport-documents.gruposoledad.com" #cambiame 
certificate:
  enabled: true
  dnsName: "transport-documents.gruposoledad.com" #cambiame 
image:
  repository: "gruposoledad/transport_documents" #cambiame 
  tag: "v2026.09.01.15.01"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: regcred
resources:
  requests:
    memory: "16Mi"
    cpu: "5m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
