<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dtd.Domain\Dtd.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" Version="2.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
    <PackageReference Include="Mapster" Version="10.0.10" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dtd.Application.Tests" />
    <InternalsVisibleTo Include="Dtd.Infrastructure" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="NewFolder\" />
  </ItemGroup>

</Project>
