// <auto-generated />
using System;
using Dtd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dtd.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DtdDbContext))]
    [Migration("20260716114007_AlmacenesYRelacionAgencias")]
    partial class AlmacenesYRelacionAgencias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dtd.Domain.Agencias.Agencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("AgenciaQs")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agencia_qs");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_agencias");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_agencias_codigo");

                    b.ToTable("agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Calle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("calle");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("empresa");

                    b.Property<string>("Municipio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("municipio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pais");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_almacenes");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_almacenes_empresa_codigo");

                    b.ToTable("almacenes", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoDigitalTransporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("AgenciaCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agencia_codigo");

                    b.Property<string>("AlmacenCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("almacen_codigo");

                    b.Property<string>("DocutenEstado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("docuten_estado");

                    b.Property<string>("DocutenId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("docuten_id");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ultimo_error");

                    b.Property<DateTimeOffset?>("UltimoErrorEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_error_en");

                    b.Property<string>("Usuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.HasIndex("Empresa", "AlmacenCodigo", "AgenciaCodigo")
                        .HasDatabaseName("ix_documentos_empresa_almacen_codigo_agencia_codigo");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.Expedicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgenciaCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agencia_codigo");

                    b.Property<string>("AlmacenCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("almacen_codigo");

                    b.Property<int>("Bultos")
                        .HasColumnType("integer")
                        .HasColumnName("bultos");

                    b.Property<string>("Cliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cliente");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("ErpId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("erp_id");

                    b.Property<string>("ExpeditionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expedition_code");

                    b.Property<int>("ExpeditionType")
                        .HasColumnType("integer")
                        .HasColumnName("expedition_type");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.HasKey("Id")
                        .HasName("pk_expediciones");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_expediciones_documento_id");

                    b.HasIndex("Empresa", "AlmacenCodigo", "AgenciaCodigo", "ErpId")
                        .IsUnique()
                        .HasDatabaseName("ix_expediciones_empresa_almacen_codigo_agencia_codigo_erp_id");

                    b.ToTable("expediciones", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.IntentoEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<int?>("EstadoHttp")
                        .HasColumnType("integer")
                        .HasColumnName("estado_http");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean")
                        .HasColumnName("exitoso");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mensaje");

                    b.Property<DateTimeOffset>("Momento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("momento");

                    b.HasKey("Id")
                        .HasName("pk_intentos_envio");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_intentos_envio_documento_id");

                    b.ToTable("intentos_envio", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Transportistas.TransportistaDefecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgenciaCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agencia_codigo");

                    b.Property<string>("ErpId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("erp_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_transportistas_defecto");

                    b.HasIndex("AgenciaCodigo", "ErpId")
                        .IsUnique()
                        .HasDatabaseName("ix_transportistas_defecto_agencia_codigo_erp_id");

                    b.ToTable("transportistas_defecto", (string)null);
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.AlmacenAgencia", b =>
                {
                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.HasKey("AlmacenId", "AgenciaId")
                        .HasName("pk_almacen_agencias");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_almacen_agencias_agencia_id");

                    b.ToTable("almacen_agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.Empresa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("BaseAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_address");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.HasKey("Codigo")
                        .HasName("pk_empresas");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.Almacen", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AlmacenId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("AlmacenId");

                            b1.ToTable("almacenes");

                            b1.WithOwner()
                                .HasForeignKey("AlmacenId")
                                .HasConstraintName("fk_almacenes_almacenes_id");
                        });

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoDigitalTransporte", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.OrigenDocumento", "Origen", b1 =>
                        {
                            b1.Property<Guid>("DocumentoDigitalTransporteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("origen_address_name");

                            b1.Property<string>("AddressPhone1")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("origen_address_phone1");

                            b1.Property<string>("AddressStreet")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("origen_address_street");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origen_city");

                            b1.Property<string>("CountryIsoCode")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("origen_country_iso_code");

                            b1.Property<string>("CountryName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origen_country_name");

                            b1.Property<string>("ProvinceName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origen_province_name");

                            b1.Property<string>("WarehouseId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("origen_warehouse_id");

                            b1.Property<string>("Zipcode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("origen_zipcode");

                            b1.HasKey("DocumentoDigitalTransporteId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoDigitalTransporteId")
                                .HasConstraintName("fk_documentos_documentos_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.RangoFechas", "RangoFechas", b1 =>
                        {
                            b1.Property<Guid>("DocumentoDigitalTransporteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("FechaDesde")
                                .HasColumnType("date")
                                .HasColumnName("fecha_desde");

                            b1.Property<DateOnly>("FechaHasta")
                                .HasColumnType("date")
                                .HasColumnName("fecha_hasta");

                            b1.HasKey("DocumentoDigitalTransporteId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoDigitalTransporteId")
                                .HasConstraintName("fk_documentos_documentos_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Transportista", "Transportista", b1 =>
                        {
                            b1.Property<Guid>("DocumentoDigitalTransporteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ErpId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("transportista_erp_id");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("transportista_nombre");

                            b1.HasKey("DocumentoDigitalTransporteId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoDigitalTransporteId")
                                .HasConstraintName("fk_documentos_documentos_id");

                            b1.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("TransportistaDocumentoDigitalTransporteId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("transportista_email");

                                    b2.HasKey("TransportistaDocumentoDigitalTransporteId");

                                    b2.ToTable("documentos");

                                    b2.WithOwner()
                                        .HasForeignKey("TransportistaDocumentoDigitalTransporteId")
                                        .HasConstraintName("fk_documentos_documentos_id");
                                });

                            b1.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Movil", "Movil", b2 =>
                                {
                                    b2.Property<Guid>("TransportistaDocumentoDigitalTransporteId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("transportista_movil");

                                    b2.HasKey("TransportistaDocumentoDigitalTransporteId");

                                    b2.ToTable("documentos");

                                    b2.WithOwner()
                                        .HasForeignKey("TransportistaDocumentoDigitalTransporteId")
                                        .HasConstraintName("fk_documentos_documentos_id");
                                });

                            b1.Navigation("Email");

                            b1.Navigation("Movil");
                        });

                    b.Navigation("Origen")
                        .IsRequired();

                    b.Navigation("RangoFechas")
                        .IsRequired();

                    b.Navigation("Transportista");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.Expedicion", b =>
                {
                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("Expediciones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expediciones_documentos_documento_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.DestinoExpedicion", "Destino", b1 =>
                        {
                            b1.Property<Guid>("ExpedicionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("destino_address_name");

                            b1.Property<string>("AddressStreet")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("destino_address_street");

                            b1.Property<string>("AlmacenDestino")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_almacen_destino");

                            b1.Property<string>("CodigoPostal")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("destino_codigo_postal");

                            b1.Property<string>("Municipio")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_municipio");

                            b1.Property<string>("Pais")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_pais");

                            b1.Property<string>("Provincia")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_provincia");

                            b1.HasKey("ExpedicionId");

                            b1.ToTable("expediciones");

                            b1.WithOwner()
                                .HasForeignKey("ExpedicionId")
                                .HasConstraintName("fk_expediciones_expediciones_id");
                        });

                    b.Navigation("Destino")
                        .IsRequired();
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.IntentoEnvio", b =>
                {
                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("IntentosEnvio")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intentos_envio_documentos_documento_id");
                });

            modelBuilder.Entity("Dtd.Domain.Transportistas.TransportistaDefecto", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("TransportistaDefectoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("TransportistaDefectoId");

                            b1.ToTable("transportistas_defecto");

                            b1.WithOwner()
                                .HasForeignKey("TransportistaDefectoId")
                                .HasConstraintName("fk_transportistas_defecto_transportistas_defecto_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Movil", "Movil", b1 =>
                        {
                            b1.Property<Guid>("TransportistaDefectoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("movil");

                            b1.HasKey("TransportistaDefectoId");

                            b1.ToTable("transportistas_defecto");

                            b1.WithOwner()
                                .HasForeignKey("TransportistaDefectoId")
                                .HasConstraintName("fk_transportistas_defecto_transportistas_defecto_id");
                        });

                    b.Navigation("Email");

                    b.Navigation("Movil")
                        .IsRequired();
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.AlmacenAgencia", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencias_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencias_almacenes_almacen_id");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoDigitalTransporte", b =>
                {
                    b.Navigation("Expediciones");

                    b.Navigation("IntentosEnvio");
                });
#pragma warning restore 612, 618
        }
    }
}

