// <auto-generated />
using System;
using Dtd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dtd.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DtdDbContext))]
    [Migration("20260729162614_EnviosDestinoEntregaSinConsigneesDocumento")]
    partial class EnviosDestinoEntregaSinConsigneesDocumento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dtd.Domain.Agencias.Agencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("AgenciaQs")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agencia_qs");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<bool>("EnvioDirecto")
                        .HasColumnType("boolean")
                        .HasColumnName("envio_directo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_agencias");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_agencias_empresa_codigo");

                    b.ToTable("agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPaisIso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_pais_iso");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_almacenes");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_almacenes_empresa_codigo");

                    b.ToTable("almacenes", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.AlmacenAgencia", b =>
                {
                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid?>("ConsigneeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignee_base_id");

                    b.HasKey("AlmacenId", "AgenciaId")
                        .HasName("pk_almacen_agencias");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_almacen_agencias_agencia_id");

                    b.HasIndex("ConsigneeBaseId")
                        .HasDatabaseName("ix_almacen_agencias_consignee_base_id");

                    b.ToTable("almacen_agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.AlmacenAgenciaCcDefecto", b =>
                {
                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid>("CcId")
                        .HasColumnType("uuid")
                        .HasColumnName("cc_id");

                    b.HasKey("AlmacenId", "AgenciaId", "CcId")
                        .HasName("pk_almacen_agencia_ccs_defecto");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_almacen_agencia_ccs_defecto_agencia_id");

                    b.HasIndex("CcId")
                        .HasDatabaseName("ix_almacen_agencia_ccs_defecto_cc_id");

                    b.ToTable("almacen_agencia_ccs_defecto", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.AlmacenAgenciaConductorDefecto", b =>
                {
                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid>("ConductorId")
                        .HasColumnType("uuid")
                        .HasColumnName("conductor_id");

                    b.HasKey("AlmacenId", "AgenciaId", "ConductorId")
                        .HasName("pk_almacen_agencia_conductores_defecto");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_almacen_agencia_conductores_defecto_agencia_id");

                    b.HasIndex("ConductorId")
                        .HasDatabaseName("ix_almacen_agencia_conductores_defecto_conductor_id");

                    b.ToTable("almacen_agencia_conductores_defecto", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.AlmacenAgenciaConsigneeDefecto", b =>
                {
                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignee_id");

                    b.HasKey("AlmacenId", "AgenciaId", "ConsigneeId")
                        .HasName("pk_almacen_agencia_consignees_defecto");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_almacen_agencia_consignees_defecto_agencia_id");

                    b.HasIndex("ConsigneeId")
                        .HasDatabaseName("ix_almacen_agencia_consignees_defecto_consignee_id");

                    b.ToTable("almacen_agencia_consignees_defecto", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Ccs.Cc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_ccs");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_ccs_empresa_codigo");

                    b.ToTable("ccs", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Ccs.CcAgencia", b =>
                {
                    b.Property<Guid>("CcId")
                        .HasColumnType("uuid")
                        .HasColumnName("cc_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.HasKey("CcId", "AgenciaId")
                        .HasName("pk_cc_agencias");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_cc_agencias_agencia_id");

                    b.ToTable("cc_agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Ccs.CcAlmacen", b =>
                {
                    b.Property<Guid>("CcId")
                        .HasColumnType("uuid")
                        .HasColumnName("cc_id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.HasKey("CcId", "AlmacenId")
                        .HasName("pk_cc_almacenes");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_cc_almacenes_almacen_id");

                    b.ToTable("cc_almacenes", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Conductores.Conductor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_conductores");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_conductores_empresa_codigo");

                    b.ToTable("conductores", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Conductores.ConductorAgencia", b =>
                {
                    b.Property<Guid>("ConductorId")
                        .HasColumnType("uuid")
                        .HasColumnName("conductor_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.HasKey("ConductorId", "AgenciaId")
                        .HasName("pk_conductor_agencias");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_conductor_agencias_agencia_id");

                    b.ToTable("conductor_agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Consignees.Consignee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPaisIso")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("codigo_pais_iso");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_consignees");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_consignees_empresa_codigo");

                    b.ToTable("consignees", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Consignees.ConsigneeAgencia", b =>
                {
                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignee_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.HasKey("ConsigneeId", "AgenciaId")
                        .HasName("pk_consignee_agencias");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_consignee_agencias_agencia_id");

                    b.ToTable("consignee_agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Consignees.ConsigneeAlmacen", b =>
                {
                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignee_id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.HasKey("ConsigneeId", "AlmacenId")
                        .HasName("pk_consignee_almacenes");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_consignee_almacenes_almacen_id");

                    b.ToTable("consignee_almacenes", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.CcAsignado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CcCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("cc_catalog_id");

                    b.Property<string>("CcCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cc_codigo");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_ccs_documento");

                    b.HasIndex("DocumentoId", "CcCatalogId")
                        .IsUnique()
                        .HasDatabaseName("ix_ccs_documento_documento_id_cc_catalog_id");

                    b.ToTable("ccs_documento", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.ConductorAsignado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConductorCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("conductor_catalog_id");

                    b.Property<string>("ConductorCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("conductor_codigo");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_conductores_documento");

                    b.HasIndex("DocumentoId", "ConductorCatalogId")
                        .IsUnique()
                        .HasDatabaseName("ix_conductores_documento_documento_id_conductor_catalog_id");

                    b.ToTable("conductores_documento", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoDigitalTransporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion");

                    b.Property<string>("TipoAgrupacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_agrupacion");

                    b.Property<string>("UsuarioGeneracionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_generacion_id");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_documentos_agencia_id");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_documentos_almacen_id");

                    b.HasIndex("Empresa", "AlmacenId", "AgenciaId")
                        .HasDatabaseName("ix_documentos_empresa_almacen_id_agencia_id");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Bultos")
                        .HasColumnType("integer")
                        .HasColumnName("bultos");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia");

                    b.HasKey("Id")
                        .HasName("pk_envios");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_envios_documento_id");

                    b.ToTable("envios", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.Expedicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<int>("Bultos")
                        .HasColumnType("integer")
                        .HasColumnName("bultos");

                    b.Property<string>("Cliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cliente");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<Guid?>("EnvioId")
                        .HasColumnType("uuid")
                        .HasColumnName("envio_id");

                    b.Property<string>("ErpId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("erp_id");

                    b.Property<string>("ExpeditionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expedition_code");

                    b.Property<int>("ExpeditionType")
                        .HasColumnType("integer")
                        .HasColumnName("expedition_type");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.HasKey("Id")
                        .HasName("pk_expediciones");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_expediciones_agencia_id");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_expediciones_almacen_id");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_expediciones_documento_id");

                    b.HasIndex("EnvioId")
                        .HasDatabaseName("ix_expediciones_envio_id");

                    b.HasIndex("Empresa", "AlmacenId", "AgenciaId", "ErpId")
                        .IsUnique()
                        .HasDatabaseName("ix_expediciones_empresa_almacen_id_agencia_id_erp_id");

                    b.ToTable("expediciones", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Empresas.Empresa", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("BaseAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_address");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.Almacen", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AlmacenId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("AlmacenId");

                            b1.ToTable("almacenes");

                            b1.WithOwner()
                                .HasForeignKey("AlmacenId")
                                .HasConstraintName("fk_almacenes_almacenes_id");
                        });

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.AlmacenAgencia", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencias_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencias_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Consignees.Consignee", null)
                        .WithMany()
                        .HasForeignKey("ConsigneeBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_almacen_agencias_consignees_consignee_base_id");
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.AlmacenAgenciaCcDefecto", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_ccs_defecto_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_ccs_defecto_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Ccs.Cc", null)
                        .WithMany()
                        .HasForeignKey("CcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_ccs_defecto_ccs_cc_id");
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.AlmacenAgenciaConductorDefecto", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_conductores_defecto_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_conductores_defecto_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Conductores.Conductor", null)
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_conductores_defecto_conductores_conductor_id");
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.AlmacenAgenciaConsigneeDefecto", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_consignees_defecto_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_consignees_defecto_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Consignees.Consignee", null)
                        .WithMany()
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_consignees_defecto_consignees_consignee_id");
                });

            modelBuilder.Entity("Dtd.Domain.Ccs.Cc", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CcId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("CcId");

                            b1.ToTable("ccs");

                            b1.WithOwner()
                                .HasForeignKey("CcId")
                                .HasConstraintName("fk_ccs_ccs_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("Dtd.Domain.Ccs.CcAgencia", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cc_agencias_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Ccs.Cc", null)
                        .WithMany()
                        .HasForeignKey("CcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cc_agencias_ccs_cc_id");
                });

            modelBuilder.Entity("Dtd.Domain.Ccs.CcAlmacen", b =>
                {
                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cc_almacenes_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Ccs.Cc", null)
                        .WithMany()
                        .HasForeignKey("CcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cc_almacenes_ccs_cc_id");
                });

            modelBuilder.Entity("Dtd.Domain.Conductores.Conductor", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Canal", "Canal", b1 =>
                        {
                            b1.Property<Guid>("ConductorId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("channel");

                            b1.HasKey("ConductorId");

                            b1.ToTable("conductores");

                            b1.WithOwner()
                                .HasForeignKey("ConductorId")
                                .HasConstraintName("fk_conductores_conductores_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ConductorId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("ConductorId");

                            b1.ToTable("conductores");

                            b1.WithOwner()
                                .HasForeignKey("ConductorId")
                                .HasConstraintName("fk_conductores_conductores_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Movil", "Movil", b1 =>
                        {
                            b1.Property<Guid>("ConductorId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("movil");

                            b1.HasKey("ConductorId");

                            b1.ToTable("conductores");

                            b1.WithOwner()
                                .HasForeignKey("ConductorId")
                                .HasConstraintName("fk_conductores_conductores_id");
                        });

                    b.Navigation("Canal")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Dtd.Domain.Conductores.ConductorAgencia", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conductor_agencias_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Conductores.Conductor", null)
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conductor_agencias_conductores_conductor_id");
                });

            modelBuilder.Entity("Dtd.Domain.Consignees.Consignee", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Canal", "Canal", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("channel");

                            b1.HasKey("ConsigneeId");

                            b1.ToTable("consignees");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeId")
                                .HasConstraintName("fk_consignees_consignees_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("ConsigneeId");

                            b1.ToTable("consignees");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeId")
                                .HasConstraintName("fk_consignees_consignees_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Movil", "Movil", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("movil");

                            b1.HasKey("ConsigneeId");

                            b1.ToTable("consignees");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeId")
                                .HasConstraintName("fk_consignees_consignees_id");
                        });

                    b.Navigation("Canal")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Dtd.Domain.Consignees.ConsigneeAgencia", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignee_agencias_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Consignees.Consignee", null)
                        .WithMany("Agencias")
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignee_agencias_consignees_consignee_id");

                    b.OwnsOne("Dtd.Domain.Consignees.DireccionConsignee", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeAgenciaConsigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("consignee_id");

                            b1.Property<Guid>("ConsigneeAgenciaAgenciaId")
                                .HasColumnType("uuid")
                                .HasColumnName("agencia_id");

                            b1.Property<string>("CodigoPaisIso")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("dir_pais");

                            b1.Property<string>("CodigoPostal")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("dir_codigo_postal");

                            b1.Property<string>("Direccion")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("dir_calle");

                            b1.Property<string>("Municipio")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("dir_municipio");

                            b1.HasKey("ConsigneeAgenciaConsigneeId", "ConsigneeAgenciaAgenciaId");

                            b1.ToTable("consignee_agencias");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeAgenciaConsigneeId", "ConsigneeAgenciaAgenciaId")
                                .HasConstraintName("fk_consignee_agencias_consignee_agencias_consignee_id_agencia_");
                        });

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("Dtd.Domain.Consignees.ConsigneeAlmacen", b =>
                {
                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignee_almacenes_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Consignees.Consignee", null)
                        .WithMany("Almacenes")
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignee_almacenes_consignees_consignee_id");

                    b.OwnsOne("Dtd.Domain.Consignees.DireccionConsignee", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeAlmacenConsigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("consignee_id");

                            b1.Property<Guid>("ConsigneeAlmacenAlmacenId")
                                .HasColumnType("uuid")
                                .HasColumnName("almacen_id");

                            b1.Property<string>("CodigoPaisIso")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("dir_pais");

                            b1.Property<string>("CodigoPostal")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("dir_codigo_postal");

                            b1.Property<string>("Direccion")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("dir_calle");

                            b1.Property<string>("Municipio")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("dir_municipio");

                            b1.HasKey("ConsigneeAlmacenConsigneeId", "ConsigneeAlmacenAlmacenId");

                            b1.ToTable("consignee_almacenes");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeAlmacenConsigneeId", "ConsigneeAlmacenAlmacenId")
                                .HasConstraintName("fk_consignee_almacenes_consignee_almacenes_consignee_id_almace");
                        });

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.CcAsignado", b =>
                {
                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("Ccs")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ccs_documento_documentos_documento_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CcAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("CcAsignadoId");

                            b1.ToTable("ccs_documento");

                            b1.WithOwner()
                                .HasForeignKey("CcAsignadoId")
                                .HasConstraintName("fk_ccs_documento_ccs_documento_id");
                        });

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.ConductorAsignado", b =>
                {
                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("Conductores")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conductores_documento_documentos_documento_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Canal", "Canal", b1 =>
                        {
                            b1.Property<Guid>("ConductorAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("channel");

                            b1.HasKey("ConductorAsignadoId");

                            b1.ToTable("conductores_documento");

                            b1.WithOwner()
                                .HasForeignKey("ConductorAsignadoId")
                                .HasConstraintName("fk_conductores_documento_conductores_documento_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ConductorAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("ConductorAsignadoId");

                            b1.ToTable("conductores_documento");

                            b1.WithOwner()
                                .HasForeignKey("ConductorAsignadoId")
                                .HasConstraintName("fk_conductores_documento_conductores_documento_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Movil", "Movil", b1 =>
                        {
                            b1.Property<Guid>("ConductorAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("movil");

                            b1.HasKey("ConductorAsignadoId");

                            b1.ToTable("conductores_documento");

                            b1.WithOwner()
                                .HasForeignKey("ConductorAsignadoId")
                                .HasConstraintName("fk_conductores_documento_conductores_documento_id");
                        });

                    b.Navigation("Canal")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoDigitalTransporte", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_almacenes_almacen_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.OrigenDocumento", "Origen", b1 =>
                        {
                            b1.Property<Guid>("DocumentoDigitalTransporteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("origen_address_name");

                            b1.Property<string>("AddressPhone1")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("origen_address_phone1");

                            b1.Property<string>("AddressStreet")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("origen_address_street");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origen_city");

                            b1.Property<string>("CountryIsoCode")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("origen_country_iso_code");

                            b1.Property<string>("CountryName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origen_country_name");

                            b1.Property<string>("ProvinceName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origen_province_name");

                            b1.Property<string>("WarehouseId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("origen_warehouse_id");

                            b1.Property<string>("Zipcode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("origen_zipcode");

                            b1.HasKey("DocumentoDigitalTransporteId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoDigitalTransporteId")
                                .HasConstraintName("fk_documentos_documentos_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.RangoFechas", "RangoFechas", b1 =>
                        {
                            b1.Property<Guid>("DocumentoDigitalTransporteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("FechaDesde")
                                .HasColumnType("date")
                                .HasColumnName("fecha_desde");

                            b1.Property<DateOnly>("FechaHasta")
                                .HasColumnType("date")
                                .HasColumnName("fecha_hasta");

                            b1.HasKey("DocumentoDigitalTransporteId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoDigitalTransporteId")
                                .HasConstraintName("fk_documentos_documentos_id");
                        });

                    b.Navigation("Origen")
                        .IsRequired();

                    b.Navigation("RangoFechas")
                        .IsRequired();
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.Envio", b =>
                {
                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("Envios")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_envios_documentos_documento_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.DestinoEnvio", "Destino", b1 =>
                        {
                            b1.Property<Guid>("EnvioId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("destino_ciudad");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_codigo");

                            b1.Property<string>("CodigoPais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("destino_codigo_pais");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("destino_codigo_postal");

                            b1.Property<string>("Direccion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("destino_direccion");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("destino_nombre");

                            b1.Property<string>("Telefono")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_telefono");

                            b1.HasKey("EnvioId");

                            b1.ToTable("envios");

                            b1.WithOwner()
                                .HasForeignKey("EnvioId")
                                .HasConstraintName("fk_envios_envios_id");
                        });

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.Expedicion", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expediciones_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expediciones_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("Expediciones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expediciones_documentos_documento_id");

                    b.HasOne("Dtd.Domain.Documentos.Envio", null)
                        .WithMany()
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expediciones_envios_envio_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.DestinoExpedicion", "Destino", b1 =>
                        {
                            b1.Property<Guid>("ExpedicionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("destino_address_name");

                            b1.Property<string>("AddressPhone1")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_address_phone1");

                            b1.Property<string>("AddressStreet")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("destino_address_street");

                            b1.Property<string>("AlmacenDestino")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_almacen_destino");

                            b1.Property<string>("CodigoPostal")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("destino_codigo_postal");

                            b1.Property<string>("Municipio")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_municipio");

                            b1.Property<string>("Pais")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_pais");

                            b1.Property<string>("Provincia")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_provincia");

                            b1.HasKey("ExpedicionId");

                            b1.ToTable("expediciones");

                            b1.WithOwner()
                                .HasForeignKey("ExpedicionId")
                                .HasConstraintName("fk_expediciones_expediciones_id");
                        });

                    b.Navigation("Destino")
                        .IsRequired();
                });

            modelBuilder.Entity("Dtd.Domain.Consignees.Consignee", b =>
                {
                    b.Navigation("Agencias");

                    b.Navigation("Almacenes");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoDigitalTransporte", b =>
                {
                    b.Navigation("Ccs");

                    b.Navigation("Conductores");

                    b.Navigation("Envios");

                    b.Navigation("Expediciones");
                });
#pragma warning restore 612, 618
        }
    }
}
