// <auto-generated />
using System;
using Dtd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dtd.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DtdDbContext))]
    [Migration("20260720170041_ConsigneesCatalogo")]
    partial class ConsigneesCatalogo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dtd.Domain.Agencias.Agencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("AgenciaQs")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agencia_qs");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_agencias");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_agencias_empresa_codigo");

                    b.ToTable("agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Calle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("calle");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("empresa");

                    b.Property<string>("Municipio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("municipio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pais");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_almacenes");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_almacenes_empresa_codigo");

                    b.ToTable("almacenes", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Conductores.Conductor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("empresa");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_conductores");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_conductores_empresa_codigo");

                    b.ToTable("conductores", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Consignees.Consignee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("empresa");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_consignees");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_consignees_empresa_codigo");

                    b.ToTable("consignees", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.ConductorAsignado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConductorCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("conductor_catalog_id");

                    b.Property<string>("ConductorCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("conductor_codigo");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_conductores_documento");

                    b.HasIndex("DocumentoId", "ConductorCatalogId")
                        .IsUnique()
                        .HasDatabaseName("ix_conductores_documento_documento_id_conductor_catalog_id");

                    b.ToTable("conductores_documento", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.ConsigneeAsignado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsigneeCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignee_catalog_id");

                    b.Property<string>("ConsigneeCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consignee_codigo");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_consignees_documento");

                    b.HasIndex("DocumentoId", "ConsigneeCatalogId")
                        .IsUnique()
                        .HasDatabaseName("ix_consignees_documento_documento_id_consignee_catalog_id");

                    b.ToTable("consignees_documento", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoDigitalTransporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<string>("DocutenEstado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("docuten_estado");

                    b.Property<string>("DocutenId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("docuten_id");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion");

                    b.Property<string>("Usuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_documentos_agencia_id");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_documentos_almacen_id");

                    b.HasIndex("Empresa", "AlmacenId", "AgenciaId")
                        .HasDatabaseName("ix_documentos_empresa_almacen_id_agencia_id");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<int?>("EstadoHttp")
                        .HasColumnType("integer")
                        .HasColumnName("estado_http");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mensaje");

                    b.Property<DateTimeOffset>("Momento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("momento");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_documento_eventos");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_documento_eventos_documento_id");

                    b.ToTable("documento_eventos", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.Expedicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<int>("Bultos")
                        .HasColumnType("integer")
                        .HasColumnName("bultos");

                    b.Property<string>("Cliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cliente");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("ErpId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("erp_id");

                    b.Property<string>("ExpeditionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expedition_code");

                    b.Property<int>("ExpeditionType")
                        .HasColumnType("integer")
                        .HasColumnName("expedition_type");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.HasKey("Id")
                        .HasName("pk_expediciones");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_expediciones_agencia_id");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_expediciones_almacen_id");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_expediciones_documento_id");

                    b.HasIndex("Empresa", "AlmacenId", "AgenciaId", "ErpId")
                        .IsUnique()
                        .HasDatabaseName("ix_expediciones_empresa_almacen_id_agencia_id_erp_id");

                    b.ToTable("expediciones", (string)null);
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.AlmacenAgencia", b =>
                {
                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.HasKey("AlmacenId", "AgenciaId")
                        .HasName("pk_almacen_agencias");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_almacen_agencias_agencia_id");

                    b.ToTable("almacen_agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.AlmacenAgenciaConductorDefecto", b =>
                {
                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid>("ConductorId")
                        .HasColumnType("uuid")
                        .HasColumnName("conductor_id");

                    b.HasKey("AlmacenId", "AgenciaId", "ConductorId")
                        .HasName("pk_almacen_agencia_conductores_defecto");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_almacen_agencia_conductores_defecto_agencia_id");

                    b.HasIndex("ConductorId")
                        .HasDatabaseName("ix_almacen_agencia_conductores_defecto_conductor_id");

                    b.ToTable("almacen_agencia_conductores_defecto", (string)null);
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.AlmacenAgenciaConsigneeDefecto", b =>
                {
                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignee_id");

                    b.HasKey("AlmacenId", "AgenciaId", "ConsigneeId")
                        .HasName("pk_almacen_agencia_consignees_defecto");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_almacen_agencia_consignees_defecto_agencia_id");

                    b.HasIndex("ConsigneeId")
                        .HasDatabaseName("ix_almacen_agencia_consignees_defecto_consignee_id");

                    b.ToTable("almacen_agencia_consignees_defecto", (string)null);
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.ConductorAgencia", b =>
                {
                    b.Property<Guid>("ConductorId")
                        .HasColumnType("uuid")
                        .HasColumnName("conductor_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.HasKey("ConductorId", "AgenciaId")
                        .HasName("pk_conductor_agencias");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_conductor_agencias_agencia_id");

                    b.ToTable("conductor_agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.ConsigneeAgencia", b =>
                {
                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignee_id");

                    b.Property<Guid>("AgenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("agencia_id");

                    b.HasKey("ConsigneeId", "AgenciaId")
                        .HasName("pk_consignee_agencias");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("ix_consignee_agencias_agencia_id");

                    b.ToTable("consignee_agencias", (string)null);
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.ConsigneeAlmacen", b =>
                {
                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignee_id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.HasKey("ConsigneeId", "AlmacenId")
                        .HasName("pk_consignee_almacenes");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_consignee_almacenes_almacen_id");

                    b.ToTable("consignee_almacenes", (string)null);
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.Empresa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("empresa");

                    b.Property<string>("BaseAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_address");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.HasKey("Codigo")
                        .HasName("pk_empresas");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Dtd.Domain.Almacenes.Almacen", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AlmacenId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("AlmacenId");

                            b1.ToTable("almacenes");

                            b1.WithOwner()
                                .HasForeignKey("AlmacenId")
                                .HasConstraintName("fk_almacenes_almacenes_id");
                        });

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Dtd.Domain.Conductores.Conductor", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Canal", "Canal", b1 =>
                        {
                            b1.Property<Guid>("ConductorId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("channel");

                            b1.HasKey("ConductorId");

                            b1.ToTable("conductores");

                            b1.WithOwner()
                                .HasForeignKey("ConductorId")
                                .HasConstraintName("fk_conductores_conductores_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ConductorId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("ConductorId");

                            b1.ToTable("conductores");

                            b1.WithOwner()
                                .HasForeignKey("ConductorId")
                                .HasConstraintName("fk_conductores_conductores_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Movil", "Movil", b1 =>
                        {
                            b1.Property<Guid>("ConductorId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("movil");

                            b1.HasKey("ConductorId");

                            b1.ToTable("conductores");

                            b1.WithOwner()
                                .HasForeignKey("ConductorId")
                                .HasConstraintName("fk_conductores_conductores_id");
                        });

                    b.Navigation("Canal")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Dtd.Domain.Consignees.Consignee", b =>
                {
                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Canal", "Canal", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("channel");

                            b1.HasKey("ConsigneeId");

                            b1.ToTable("consignees");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeId")
                                .HasConstraintName("fk_consignees_consignees_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("ConsigneeId");

                            b1.ToTable("consignees");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeId")
                                .HasConstraintName("fk_consignees_consignees_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Movil", "Movil", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("movil");

                            b1.HasKey("ConsigneeId");

                            b1.ToTable("consignees");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeId")
                                .HasConstraintName("fk_consignees_consignees_id");
                        });

                    b.Navigation("Canal")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.ConductorAsignado", b =>
                {
                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("Conductores")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conductores_documento_documentos_documento_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Canal", "Canal", b1 =>
                        {
                            b1.Property<Guid>("ConductorAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("channel");

                            b1.HasKey("ConductorAsignadoId");

                            b1.ToTable("conductores_documento");

                            b1.WithOwner()
                                .HasForeignKey("ConductorAsignadoId")
                                .HasConstraintName("fk_conductores_documento_conductores_documento_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ConductorAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("ConductorAsignadoId");

                            b1.ToTable("conductores_documento");

                            b1.WithOwner()
                                .HasForeignKey("ConductorAsignadoId")
                                .HasConstraintName("fk_conductores_documento_conductores_documento_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Movil", "Movil", b1 =>
                        {
                            b1.Property<Guid>("ConductorAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("movil");

                            b1.HasKey("ConductorAsignadoId");

                            b1.ToTable("conductores_documento");

                            b1.WithOwner()
                                .HasForeignKey("ConductorAsignadoId")
                                .HasConstraintName("fk_conductores_documento_conductores_documento_id");
                        });

                    b.Navigation("Canal")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.ConsigneeAsignado", b =>
                {
                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("Consignees")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignees_documento_documentos_documento_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Canal", "Canal", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("channel");

                            b1.HasKey("ConsigneeAsignadoId");

                            b1.ToTable("consignees_documento");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeAsignadoId")
                                .HasConstraintName("fk_consignees_documento_consignees_documento_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.HasKey("ConsigneeAsignadoId");

                            b1.ToTable("consignees_documento");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeAsignadoId")
                                .HasConstraintName("fk_consignees_documento_consignees_documento_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.Movil", "Movil", b1 =>
                        {
                            b1.Property<Guid>("ConsigneeAsignadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("movil");

                            b1.HasKey("ConsigneeAsignadoId");

                            b1.ToTable("consignees_documento");

                            b1.WithOwner()
                                .HasForeignKey("ConsigneeAsignadoId")
                                .HasConstraintName("fk_consignees_documento_consignees_documento_id");
                        });

                    b.Navigation("Canal")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoDigitalTransporte", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_almacenes_almacen_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.OrigenDocumento", "Origen", b1 =>
                        {
                            b1.Property<Guid>("DocumentoDigitalTransporteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("origen_address_name");

                            b1.Property<string>("AddressPhone1")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("origen_address_phone1");

                            b1.Property<string>("AddressStreet")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("origen_address_street");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origen_city");

                            b1.Property<string>("CountryIsoCode")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("origen_country_iso_code");

                            b1.Property<string>("CountryName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origen_country_name");

                            b1.Property<string>("ProvinceName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origen_province_name");

                            b1.Property<string>("WarehouseId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("origen_warehouse_id");

                            b1.Property<string>("Zipcode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("origen_zipcode");

                            b1.HasKey("DocumentoDigitalTransporteId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoDigitalTransporteId")
                                .HasConstraintName("fk_documentos_documentos_id");
                        });

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.RangoFechas", "RangoFechas", b1 =>
                        {
                            b1.Property<Guid>("DocumentoDigitalTransporteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("FechaDesde")
                                .HasColumnType("date")
                                .HasColumnName("fecha_desde");

                            b1.Property<DateOnly>("FechaHasta")
                                .HasColumnType("date")
                                .HasColumnName("fecha_hasta");

                            b1.HasKey("DocumentoDigitalTransporteId");

                            b1.ToTable("documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoDigitalTransporteId")
                                .HasConstraintName("fk_documentos_documentos_id");
                        });

                    b.Navigation("Origen")
                        .IsRequired();

                    b.Navigation("RangoFechas")
                        .IsRequired();
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoEvento", b =>
                {
                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("Eventos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documento_eventos_documentos_documento_id");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.Expedicion", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expediciones_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expediciones_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Documentos.DocumentoDigitalTransporte", null)
                        .WithMany("Expediciones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expediciones_documentos_documento_id");

                    b.OwnsOne("Dtd.Domain.Documentos.ValueObjects.DestinoExpedicion", "Destino", b1 =>
                        {
                            b1.Property<Guid>("ExpedicionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("destino_address_name");

                            b1.Property<string>("AddressStreet")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("destino_address_street");

                            b1.Property<string>("AlmacenDestino")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_almacen_destino");

                            b1.Property<string>("CodigoPostal")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("destino_codigo_postal");

                            b1.Property<string>("Municipio")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_municipio");

                            b1.Property<string>("Pais")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_pais");

                            b1.Property<string>("Provincia")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("destino_provincia");

                            b1.HasKey("ExpedicionId");

                            b1.ToTable("expediciones");

                            b1.WithOwner()
                                .HasForeignKey("ExpedicionId")
                                .HasConstraintName("fk_expediciones_expediciones_id");
                        });

                    b.Navigation("Destino")
                        .IsRequired();
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.AlmacenAgencia", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencias_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencias_almacenes_almacen_id");
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.AlmacenAgenciaConductorDefecto", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_conductores_defecto_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_conductores_defecto_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Conductores.Conductor", null)
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_conductores_defecto_conductores_conductor_id");
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.AlmacenAgenciaConsigneeDefecto", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_consignees_defecto_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_consignees_defecto_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Consignees.Consignee", null)
                        .WithMany()
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_almacen_agencia_consignees_defecto_consignees_consignee_id");
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.ConductorAgencia", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conductor_agencias_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Conductores.Conductor", null)
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conductor_agencias_conductores_conductor_id");
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.ConsigneeAgencia", b =>
                {
                    b.HasOne("Dtd.Domain.Agencias.Agencia", null)
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignee_agencias_agencias_agencia_id");

                    b.HasOne("Dtd.Domain.Consignees.Consignee", null)
                        .WithMany()
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignee_agencias_consignees_consignee_id");
                });

            modelBuilder.Entity("Dtd.Infrastructure.Persistence.ConsigneeAlmacen", b =>
                {
                    b.HasOne("Dtd.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignee_almacenes_almacenes_almacen_id");

                    b.HasOne("Dtd.Domain.Consignees.Consignee", null)
                        .WithMany()
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignee_almacenes_consignees_consignee_id");
                });

            modelBuilder.Entity("Dtd.Domain.Documentos.DocumentoDigitalTransporte", b =>
                {
                    b.Navigation("Conductores");

                    b.Navigation("Consignees");

                    b.Navigation("Eventos");

                    b.Navigation("Expediciones");
                });
#pragma warning restore 612, 618
        }
    }
}
